# Windows: install MinGW for compile
# https://code.visualstudio.com/docs/languages/cpp#_example-install-mingwx64

# Windows: terminal command to build project
# mingw32-male.exe

all:
	gcc -Wall main.c file_img.c